export { default as Bag } from './Bag'
export { default as Sun } from './Sun'
export { default as Moon } from './Moon'
export { default as Menu } from './Menu'
export { default as Info } from './Info'
export { default as Star } from './Star'
export { default as Plus } from './Plus'
export { default as Heart } from './Heart'
export { default as Trash } from './Trash'
export { default as Cross } from './Cross'
export { default as Minus } from './Minus'
export { default as Check } from './Check'
export { default as Github } from './Github'
export { default as Vercel } from './Vercel'
export { default as MapPin } from './MapPin'
export { default as ArrowLeft } from './ArrowLeft'
export { default as ArrowRight } from './ArrowRight'
export { default as CreditCard } from './CreditCard'
export { default as ChevronUp } from './ChevronUp'
export { default as ChevronLeft } from './ChevronLeft'
export { default as ChevronDown } from './ChevronDown'
export { default as ChevronRight } from './ChevronRight'
export { default as DoubleChevron } from './DoubleChevron'
export {default as FaceBook} from './FaceBook'
export {default as InstaGram} from './Instagram'
export {default as Twitter} from './Twitter'
export {default as LinkedIn} from './LinkedIn'
export {default as Search} from './Search'
export {default as Cart} from './Cart'
export {default as Person} from './Person'
export {default as EyeSlash} from './EyeSlash'
export {default as GMail} from './GMail'
export {default as DeliveryTruck} from './DeliveryTruck'
export {default as PaymentIcon} from './PaymentIcon'
export {default as DHLIcon} from './DHLIcon';
export {default as MasterCardIcon} from './MasterCardIcon';
export {default as EyeIcon} from './EyeIcon';
export {default as HomeIcon} from './HomeIcon';
